# This is a config for E2B sandbox template.
# You can use template ID (l701lfig0sl6wo1csche) or template name (test-pro-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("test-pro-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("test-pro-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('test-pro-2')

team_id = "5c83af33-7d37-4809-94a5-338631980f0c"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "test-pro-2"
template_id = "l701lfig0sl6wo1csche"